spring.datasource.url=jdbc:postgresql://localhost:5432/futbol
spring.datasource.username=postgres
spring.datasource.password=19Felicianos

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

football.api.token=974117bb0a584a0cb00238562e436a8d
football.api.url=https://api.football-data.org/v4

server.port=8080